# Generated by Django 4.1.4 on 2023-07-30 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Call",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("call_type", models.CharField(default="Physical", max_length=100)),
                ("call_category", models.CharField(default="Sale", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel_type",
                    models.CharField(default="Physical Visit", max_length=100),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payment_mode", models.CharField(default=None, max_length=100)),
                (
                    "payment_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("cheque_date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Representative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("date", models.DateTimeField(default="2023-06-06")),
                ("region", models.CharField(default="Nairobi", max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("comments", models.TextField(default="No Comment")),
                (
                    "call",
                    models.ForeignKey(
                        default="Physical",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.call",
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        default="Physical Visit",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.channel",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.customer"
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.payment",
                    ),
                ),
                (
                    "representative",
                    models.ForeignKey(
                        default="None",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.representative",
                    ),
                ),
            ],
        ),
    ]
